modLoader="javafml"
license="GNU LESSER GENERAL PUBLIC LICENSE"
loaderVersion="[40,)"

[[mods]]
modId="craid"
version="1.0"
displayName="Custom Raid"
authors="_HungTeen_, cnlimiter"
#logoFile="logo.png"
displayURL="https://space.bilibili.com/362855464"
credits="Nope"
description="help players make custom raids easily"

[[dependencies.craid]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
