modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_display_url}"
logoFile = "${mod_logo_file}"
authors = "${mod_authors}"
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description = '''${mod_description}'''

#[[accessTransformers]]
#file = "META-INF/accesstransformer.cfg"
#
#[[mixins]]
#config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]] #optional
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "htlib"
type = "required"
versionRange = "${htlib_version_range}"
ordering = "NONE"
side = "BOTH"